"""Core package for the Semiconductor Yield RCA Multi-Agent MVP."""

from __future__ import annotations

from yield_rca_core.evidence_builder import EvidenceBuilder, LegacyEvidenceAdapter
from yield_rca_core.evidence_collection import EvidenceCollection
from yield_rca_core.evidence_models import (
    EVIDENCE_SCHEMA_VERSION,
    EntityType,
    EvidenceEntity,
    EvidenceType,
)
from yield_rca_core.hypothesis_engine import HypothesisEngine
from yield_rca_core.improvement_agent import ImprovementAgent
from yield_rca_core.intent_planner import QwenIntentPlanner, QwenIntentPlannerError
from yield_rca_core.investigation_models import (
    MAX_CROSS_DOMAIN_ACTIONS,
    MAX_INITIAL_QUESTIONS,
    CapabilityNotice,
    DecisionEvaluation,
    DecisionType,
    EvidenceGapStatus,
    IntentPlan,
    InvestigationAction,
    InvestigationGoal,
    InvestigationIntent,
    InvestigationQuestion,
    InvestigationValidationError,
    PlannerDecision,
    PlannerDecisionOutcome,
    QuestionKind,
    QuestionUpdate,
    QuestionUpdateDisposition,
    QuestionUpdateReasonCode,
    QuestionUpdateReview,
    RunEvaluation,
)
from yield_rca_core.knowledge_retrieval import (
    KeywordRetriever,
    KnowledgeAsset,
    KnowledgeAssetDocument,
    KnowledgeAssetRepository,
    RetrievalHit,
    RetrievalQuery,
    RetrievalResult,
    Retriever,
)
from yield_rca_core.memory_models import (
    ApprovalDecision,
    EngineerRole,
    KnowledgeIndexStatus,
    MemoryApproval,
    MemoryCandidate,
    MemoryCandidateStatus,
)
from yield_rca_core.models import (
    SCHEMA_VERSION,
    AgentFinding,
    AgentKind,
    AgentMode,
    AgentTask,
    Evidence,
    EvidenceSourceType,
    FindingKind,
    Hypothesis,
    HypothesisStatus,
    InvestigationMode,
    LLMUsageEvent,
    LotDrivenRCAError,
    LotNotFoundError,
    ModelValidationError,
    RCAJob,
    RCAState,
    Report,
    Severity,
    TaskPlan,
    TaskStatus,
    ToolInput,
    ToolOutput,
    Warning,
)
from yield_rca_core.next_action_planner import (
    LLM_REACT_ACTION_REGISTRY,
    LLM_REACT_EXECUTABLE_ACTION_KINDS,
    QwenNextActionPlanner,
    QwenNextActionPlannerError,
)
from yield_rca_core.planner_agent import (
    DEFAULT_PLANNABLE_AGENTS,
    PlannerAgent,
    PlannerConfigurationError,
)
from yield_rca_core.question_capability import (
    QUESTION_CAPABILITY_REGISTRY,
    QuestionCapabilityDefinition,
    QuestionCapabilityError,
    action_scope_matches_question,
    capability_for_question,
    capability_notice_for,
    compatible_actions_for_question,
    requested_capability_notices,
    validate_action_for_questions,
)
from yield_rca_core.question_update_review import (
    review_question_updates,
    review_qwen_planner_output,
)
from yield_rca_core.rca_reasoning_agent import SPECIALIST_AGENTS, RCAReasoningAgent
from yield_rca_core.report_generator import ReportGenerationError, ReportGenerator
from yield_rca_core.repositories import CsvFabRepository, FabRepository, PostgresFabRepository
from yield_rca_core.spc_engine import (
    calculate_imr,
    calculate_p_chart,
    calculate_xbar,
    evaluate_nelson_rules,
)
from yield_rca_core.spc_models import (
    SpcCapabilityResult,
    SpcChartResult,
    SpcChartType,
    SpcRuleViolation,
    SpcSample,
)
from yield_rca_core.specialist_agents import DefectWATAgent, FDCAgent, KnowledgeAgent, MESAgent
from yield_rca_core.supervisor import (
    SUPERVISOR_EXECUTABLE_AGENTS,
    Supervisor,
    SupervisorExecutionError,
)
from yield_rca_core.tool_layer import (
    AnalyzeLotGenealogyTool,
    AnalyzeParameterShiftTool,
    AnalyzeSpcEvidenceTool,
    FindAffectedLotsTool,
    FindImpactLotsTool,
    FindOocEventsTool,
    GetLotContextTool,
    PerformBasicSpcAnalysisTool,
    RetrieveSimilarCaseTool,
    SummarizeDefectWatTool,
)
from yield_rca_core.workflow import (
    PurePythonRCAWorkflow,
    build_csv_workflow,
    build_postgres_workflow,
    build_workflow,
)

__all__ = [
    "AgentFinding",
    "AgentKind",
    "AgentMode",
    "AgentTask",
    "ApprovalDecision",
    "AnalyzeLotGenealogyTool",
    "AnalyzeParameterShiftTool",
    "AnalyzeSpcEvidenceTool",
    "CsvFabRepository",
    "DefectWATAgent",
    "DEFAULT_PLANNABLE_AGENTS",
    "DecisionEvaluation",
    "CapabilityNotice",
    "DecisionType",
    "EVIDENCE_SCHEMA_VERSION",
    "Evidence",
    "EvidenceBuilder",
    "EvidenceCollection",
    "EvidenceEntity",
    "EvidenceGapStatus",
    "EvidenceSourceType",
    "EvidenceType",
    "EntityType",
    "EngineerRole",
    "FabRepository",
    "FDCAgent",
    "FindingKind",
    "FindAffectedLotsTool",
    "FindImpactLotsTool",
    "FindOocEventsTool",
    "Hypothesis",
    "HypothesisEngine",
    "HypothesisStatus",
    "ImprovementAgent",
    "IntentPlan",
    "InvestigationAction",
    "InvestigationGoal",
    "InvestigationIntent",
    "InvestigationMode",
    "InvestigationQuestion",
    "InvestigationValidationError",
    "KnowledgeAgent",
    "KnowledgeAsset",
    "KnowledgeAssetDocument",
    "KnowledgeAssetRepository",
    "KnowledgeIndexStatus",
    "KeywordRetriever",
    "GetLotContextTool",
    "LotDrivenRCAError",
    "LotNotFoundError",
    "LLMUsageEvent",
    "LegacyEvidenceAdapter",
    "LLM_REACT_ACTION_REGISTRY",
    "LLM_REACT_EXECUTABLE_ACTION_KINDS",
    "MAX_CROSS_DOMAIN_ACTIONS",
    "MAX_INITIAL_QUESTIONS",
    "MESAgent",
    "MemoryApproval",
    "MemoryCandidate",
    "MemoryCandidateStatus",
    "ModelValidationError",
    "PlannerAgent",
    "PlannerConfigurationError",
    "PlannerDecision",
    "PlannerDecisionOutcome",
    "QuestionUpdate",
    "QuestionUpdateDisposition",
    "QuestionUpdateReasonCode",
    "QuestionUpdateReview",
    "QuestionKind",
    "QUESTION_CAPABILITY_REGISTRY",
    "QuestionCapabilityDefinition",
    "QuestionCapabilityError",
    "action_scope_matches_question",
    "capability_for_question",
    "capability_notice_for",
    "compatible_actions_for_question",
    "requested_capability_notices",
    "validate_action_for_questions",
    "PerformBasicSpcAnalysisTool",
    "PostgresFabRepository",
    "PurePythonRCAWorkflow",
    "QwenIntentPlanner",
    "QwenIntentPlannerError",
    "QwenNextActionPlanner",
    "QwenNextActionPlannerError",
    "RCAJob",
    "RCAReasoningAgent",
    "RCAState",
    "RetrieveSimilarCaseTool",
    "RetrievalHit",
    "RetrievalQuery",
    "RetrievalResult",
    "Retriever",
    "Report",
    "ReportGenerationError",
    "ReportGenerator",
    "RunEvaluation",
    "SCHEMA_VERSION",
    "Severity",
    "SPECIALIST_AGENTS",
    "SUPERVISOR_EXECUTABLE_AGENTS",
    "Supervisor",
    "SupervisorExecutionError",
    "SpcCapabilityResult",
    "SpcChartResult",
    "SpcChartType",
    "SpcRuleViolation",
    "SpcSample",
    "SummarizeDefectWatTool",
    "TaskPlan",
    "TaskStatus",
    "ToolInput",
    "ToolOutput",
    "Warning",
    "build_csv_workflow",
    "build_postgres_workflow",
    "build_workflow",
    "calculate_imr",
    "calculate_p_chart",
    "calculate_xbar",
    "evaluate_nelson_rules",
    "review_question_updates",
    "review_qwen_planner_output",
    "__version__",
]

__version__ = "0.1.0"
